name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "ebruskokos"       # Hardcoded username
          password: "73ybdsbhdfb dbs"  # Hardcoded token
      -
        name: Get the latest tag
        id: get_tag
        run: |
          git fetch --tags
          latest_tag=$(git tag --list --sort=-v:refname | head -n 1)
          if [ -z "$latest_tag" ]; then
            echo "1.1.0" > .version
          else
            major=$(echo $latest_tag | cut -d '.' -f1)
            minor=$(echo $latest_tag | cut -d '.' -f2)
            patch=$(echo $latest_tag | cut -d '.' -f3)
            
            # Increment the minor version until it reaches 12
            if [ "$minor" -lt 12 ]; then
              minor=$((minor + 1))
            else
              minor=1
              major=$((major + 1))
            fi
            
            echo "$major.$minor.0" > .version
          fi
          echo "Version=$(cat .version)" >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ebrustokos/e-store:${{ env.Version }}
